### ISSUE TITLE
Input output error,in appengine 

### ISSUE THREAD

**Issue by Ankit-jhunjhunwala22** [inconshreveable/sqltap#29]
not able to generate report.html ,

**Comment by inconshreveable** [comment]
Without additional details about the exact environment and error message, there's probably not much we can do to help. Do you have more details?

**Comment by Ankit-jhunjhunwala22** [comment]
src: here what  I am trying to do
       profiler = sqltap.start()
        print "profiler",profiler
        projectlist_query = " // query "
        statistics = profiler.collect()
        print "statistics",statistics 
        sqltap.report(statistics,  "report.html")


This is google app engine console.
statistics []

ERROR    2015-12-18 09:00:11,105 app.py:1423] Exception on /api/projects [GET]

Traceback (most recent call last):

  File "./library\flask\app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

  File "./library\flask\app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "./library\flask\app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "./library\flask\app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

  File "./library\flask\app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "C:\Users\HP\Documents\vector\Server\src\controller\projects.py", line 237, in get_relevant

    sqltap.report(statistics,  "report.html")

  File "./library\sqltap\sqltap.py", line 307, in report

    with open(filename, 'w') as f:

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\python\stubs.py", line 247, in __init__

    raise IOError(errno.EROFS, 'Read-only file system', filename)

IOError: [Errno 30] Read-only file system: 'report.html'

**Comment by inconshreveable** [comment]
This error is a result of the report being written out to a file but the environment you're running in has a read-only file system so that operation is not permitted. This is expected behavior. You could use the wsgi-based middleware reporter in this situation.
